name: Compile, Build, and Release Java GUIs

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      release_type:
        description: "Set to 'main' for main release, leave empty for pre-release"
        required: false
        default: ""

permissions:
  contents: write   # needed to create releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # Build CRencodingGUI
      - name: Compile CRencodingGUI
        run: |
          mkdir -p target/CRencodingGUI
          javac -d target/CRencodingGUI CRencodingGUI.java
          jar cfe target/CRencodingGUI.jar CRencodingGUI -C target/CRencodingGUI .

      # Build CRhashingGUI
      - name: Compile CRhashingGUI
        run: |
          mkdir -p target/CRhashingGUI
          javac -d target/CRhashingGUI CRhashingGUI.java
          jar cfe target/CRhashingGUI.jar CRhashingGUI -C target/CRhashingGUI .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          prerelease: ${{ inputs.release_type != 'main' }}
          files: |
            target/CRencodingGUI.jar
            target/CRhashingGUI.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
