name: Compile and Build Java Projects

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # Build first project
      - name: Compile CRencodingGUI project
        run: |
          mkdir -p target/CRencodingGUI
          javac -d target/CRencodingGUI $(find * -name "*.java" ! -name "CRhashingGUI.java")

      # Build second project
      - name: Compile CRhashingGUI project
        run: |
          mkdir -p target/CRhashingGUI
          javac -d target/CRhashingGUI $(find * -name "*.java" ! -name "CRencodingGUI.java")
