name: Compile, Build, and Release Java GUIs

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      release_type:
        description: "Set to 'main' for main release, leave empty for pre-release"
        required: false
        default: ""

permissions:
  contents: write   # needed to create releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # Build CRencodingGUI
      - name: Compile CRencodingGUI
        run: |
          mkdir -p target/CRencodingGUI
          javac -d target/CRencodingGUI $(find . -name "*.java" ! -name "CRhashingGUI.java")
          jar cfe target/CRencodingGUI.jar CRencodingGUI -C target/CRencodingGUI .

      # Build CRhashingGUI
      - name: Compile CRhashingGUI
        run: |
          mkdir -p target/CRhashingGUI
          javac -d target/CRhashingGUI $(find . -name "*.java" ! -name "CRencodingGUI.java")
          jar cfe target/CRhashingGUI.jar CRhashingGUI -C target/CRhashingGUI .

      # Test builds
      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Test CRencodingGUI jar with Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          java -jar target/CRencodingGUI.jar || true

      - name: Test CRhashingGUI jar with Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          java -jar target/CRhashingGUI.jar || true

      # Create release with functional JARs
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          prerelease: ${{ inputs.release_type != 'main' }}
          files: |
            target/CRencodingGUI.jar
            target/CRhashingGUI.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
